### ISSUE TITLE
uriPrefix do not work

### ISSUE THREAD

**Issue by clycheng2015** [Minishlink/DailyScrum#27]
hello,
one day,I have see your code in Secens(maybe name is right),as I see your uriPrefix config with redux and react-navigation, it let me thunk my problem as deep linking can not work, so I do as your code config,but ...,It does not work ,I still can not jump from Android to Rn inner page ,I use react-navigation and redux ,that same to you ,I do not thnow why?can you tell me why?and your project deep linking work?

**Comment by Minishlink** [comment]
Hello,

Please follow the [React Native docs](https://facebook.github.io/react-native/docs/linking.html) and [React Navigation docs](https://reactnavigation.org/docs/deep-linking.html). Everything is explained there :)
